export const dataofUseras =  [
    { id: 1, name: "Emma Thompson" },
    { id: 2, name: "Liam Chen" },
    { id: 3, name: "Sofia Rodriguez" },
    { id: 4, name: "Noah Kim" },
    { id: 5, name: "Olivia Patel" },
    { id: 6, name: "Lucas Williams" },
    { id: 7, name: "Ava Martinez" },
    { id: 8, name: "Ethan Johnson" },
    { id: 9, name: "Isabella Lee" },
    { id: 10, name: "Mason Garcia" },
    { id: 11, name: "Sophia Anderson" },
    { id: 12, name: "Jackson Smith" },
    { id: 13, name: "Mia Wilson" },
    { id: 14, name: "Alexander Brown" },
    { id: 15, name: "Charlotte Davis" },
    { id: 16, name: "Benjamin Taylor" },
    { id: 17, name: "Amelia White" },
    { id: 18, name: "William Moore" },
    { id: 19, name: "Harper Thomas" },
    { id: 20, name: "Daniel Miller" },
    { id: 21, name: "Evelyn Jones" },
    { id: 22, name: "James Wilson" },
    { id: 23, name: "Victoria Clark" },
    { id: 24, name: "Henry Zhang" },
    { id: 25, name: "Scarlett Adams" },
    { id: 26, name: "Sebastian Scott" },
    { id: 27, name: "Chloe Murphy" },
    { id: 28, name: "Samuel Turner" },
    { id: 29, name: "Grace Phillips" },
    { id: 30, name: "David Cooper" },
  ]

  export const commentsData = [
    {
      id: 1,
      title: "Main Discussion Thread",
      votes: 145,
      time: "2024-12-23T10:30:00Z",
      children: [
        {
          id: 11,
          title: "First Response",
          votes: 42,
          time: "2024-12-23T10:35:00Z",
          children: [],
        },
        {
          id: 12,
          title: "Second Response",
          votes: 28,
          time: "2024-12-23T10:40:00Z",
          children: [
            {
              id: 121,
              title: "Reply to Second",
              votes: 15,
              time: "2024-12-23T10:45:00Z",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 2,
      title: "Technical Discussion",
      votes: 89,
      time: "2024-12-23T11:00:00Z",
      children: [
        {
          id: 21,
          title: "Technical Answer",
          votes: 56,
          time: "2024-12-23T11:15:00Z",
          children: [],
        },
      ],
    },
    {
      id: 3,
      title: "Feature Request",
      votes: 234,
      time: "2024-12-23T12:00:00Z",
      children: [],
    },
    {
      id: 4,
      title: "Bug Report",
      votes: 167,
      time: "2024-12-23T13:00:00Z",
      children: [
        {
          id: 41,
          title: "Bug Confirmation",
          votes: 45,
          time: "2024-12-23T13:30:00Z",
          children: [
            {
              id: 411,
              title: "Solution Proposed",
              votes: 78,
              time: "2024-12-23T14:00:00Z",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 5,
      title: "Community Update",
      votes: 312,
      time: "2024-12-23T15:00:00Z",
      children: [
        {
          id: 51,
          title: "Feedback",
          votes: 89,
          time: "2024-12-23T15:30:00Z",
          children: [],
        },
      ],
    },
    {
      id: 6,
      title: "Product Launch",
      votes: 445,
      time: "2024-12-23T16:00:00Z",
      children: [
        {
          id: 61,
          title: "Launch Question",
          votes: 67,
          time: "2024-12-23T16:15:00Z",
          children: [
            {
              id: 611,
              title: "Official Response",
              votes: 156,
              time: "2024-12-23T16:30:00Z",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 7,
      title: "Tutorial Thread",
      votes: 278,
      time: "2024-12-23T17:00:00Z",
      children: [],
    },
    {
      id: 8,
      title: "API Documentation",
      votes: 189,
      time: "2024-12-23T18:00:00Z",
      children: [
        {
          id: 81,
          title: "Documentation Clarification",
          votes: 45,
          time: "2024-12-23T18:30:00Z",
          children: [],
        },
      ],
    },
    {
      id: 9,
      title: "Release Notes",
      votes: 267,
      time: "2024-12-23T19:00:00Z",
      children: [],
    },
    {
      id: 10,
      title: "Community Poll",
      votes: 534,
      time: "2024-12-23T20:00:00Z",
      children: [
        {
          id: 101,
          title: "Poll Results",
          votes: 234,
          time: "2024-12-23T21:00:00Z",
          children: [
            {
              id: 1011,
              title: "Results Analysis",
              votes: 167,
              time: "2024-12-23T22:00:00Z",
              children: [],
            },
          ],
        },
      ],
    },
  ]