import React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { ChevronRight } from "lucide-react"; // Example separator icon

const Breadcrumbs = ({ items, separator, className }) => {
  const router = useRouter();

  const autoGeneratedItems = router.pathname
    .split("/")
    .filter(Boolean)
    .map((i) => {
      return {
        label: i,
        href: i,
      };
    });

  const breadcrumbs = items || autoGeneratedItems;

  return (
    <nav className={`flex items-center space-x-2 text-gray-400 ${className}`}>
      {breadcrumbs.map((item, index) => (
        <div key={item.href || item.label} className="flex items-center">
          {item.href ? (
            <Link href={item.href} className="hover:text-blue-600 transition">
              {item.label}
            </Link>
          ) : item.onClick ? (
            <button onClick={item.onClick} className="hover:text-blue-600 transition">
              {item.label}
            </button>
          ) : (
            <span className="text-gray-500">{item.label}</span>
          )}

          {index < breadcrumbs.length - 1 && <span className="mx-1">{separator || <ChevronRight size={16} />}</span>}
        </div>
      ))}
    </nav>
  );
};

export default Breadcrumbs;
